jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/restaurant #change this to your database url
    password: 0040105715@Petmax.com #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

mail:
  host: smtp.titan.email
  port: 587
  username: serve.restaurant@3dotsstudios.com
  password: 0040105715@3dots
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

SERVER_PORT: 8081
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}

